networks:
  codedesk-net:
    external: false

services:
  codedesk-server:
    container_name: codedesk-server
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21117:21117
      - 21118:21118
      - 21119:21119
    image: ${CODEDESK_SERVER_IMAGE:-codedesk-server:local}
    build:
      context: ..
      dockerfile: server/docker/Dockerfile
    environment:
      RELAY: "${RELAY:-}"
      ENCRYPTED_ONLY: "${ENCRYPTED_ONLY:-0}"
    volumes:
      - ./data:/data
    networks:
      - codedesk-net
    restart: unless-stopped
