#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/codedesk/codedesk /usr/bin/codedesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/codedesk.service ]; then
			rm /etc/systemd/system/codedesk.service /usr/lib/systemd/system/codedesk.service /usr/lib/systemd/user/codedesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/codedesk/files/systemd/codedesk.service /usr/lib/systemd/system/codedesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload codedesk.service: Unit codedesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/codedesk.service:10: Executable path is not absolute: pkill -f "codedesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/codedesk.service
		fi
		systemctl daemon-reload
		systemctl enable codedesk
		systemctl start codedesk
	fi
fi
